// SPDX-License-Identifier: Apache-2.0
//
// AUTO-GENERATED by scripts/gen-surface-ts.mjs from spec.openRPC — do not edit by hand.
// Regenerate: `node scripts/gen-surface-ts.mjs`. Checked stale by `npm test` (`--check`) and
// checked for real by `npm run typecheck`, which is the actual assertion this file exists for:
// each line below only compiles when the entry point's exported name has the type openRPC
// declares for it, or is missing/misnamed entirely, which is exactly what a divergence is.

import { BuildError, DigestError, RefIdError, SerialiseError, SpecIntegrityError, SpecVersionError, build, canonicalIdentifier, canonicalise, covers, digest, loadSpec, loadSpecFrom, parse, relate, sameIdentifier, samePackage, serialise, validateEnvelope, verdict } from "../src/index.ts"
import type { BuildParts, EnvelopeResult, Fragment, IdentifierOrParsed, NestedQualifierValue, Pair, ParseResult, QualifierRelation, RelateResult, Relation, Spec, VerdictResult } from "../src/index.ts"

// --- one assignment per openRPC method: the imported function against its declared signature ---

const _parse: (input: string) => ParseResult = parse
const _serialise: (parsed: ParseResult) => string = serialise
const _build: (parts: BuildParts) => string = build
const _canonicalIdentifier: (identifier: string | ParseResult) => string = canonicalIdentifier
const _sameIdentifier: (a: string | ParseResult, b: string | ParseResult) => boolean = sameIdentifier
const _samePackage: (a: string | ParseResult, b: string | ParseResult) => boolean = samePackage
const _covers: (general: string | ParseResult, specific: string | ParseResult) => boolean = covers
const _relate: (a: string | ParseResult, b: string | ParseResult) => RelateResult | null = relate
const _verdict: (a: string | ParseResult, b: string | ParseResult) => VerdictResult | null = verdict
const _digest: (members: readonly string[]) => string = digest
const _validateEnvelope: (requestedId: string, envelope: unknown) => EnvelopeResult = validateEnvelope
const _canonicalise: (value: unknown) => string = canonicalise
const _loadSpec: () => Spec = loadSpec
const _loadSpecFrom: (directory: string) => Spec = loadSpecFrom

// --- one type-level assertion per named value type: the exported type exists under this name ---

type _Pair = Pair
type _Fragment = Fragment
type _ParseResult = ParseResult
type _NestedQualifierValue = NestedQualifierValue
type _BuildParts = BuildParts
type _EnvelopeResult = EnvelopeResult
type _Relation = Relation
type _QualifierRelation = QualifierRelation
type _RelateResult = RelateResult
type _VerdictResult = VerdictResult
type _IdentifierOrParsed = IdentifierOrParsed
type _Spec = Spec

// --- error hierarchy: every declared error kind's class extends RefIdError ---

declare const _instance_BuildError: InstanceType<typeof BuildError>
const _isRefIdError_BuildError: RefIdError = _instance_BuildError
declare const _instance_DigestError: InstanceType<typeof DigestError>
const _isRefIdError_DigestError: RefIdError = _instance_DigestError
declare const _instance_SerialiseError: InstanceType<typeof SerialiseError>
const _isRefIdError_SerialiseError: RefIdError = _instance_SerialiseError
declare const _instance_SpecIntegrityError: InstanceType<typeof SpecIntegrityError>
const _isRefIdError_SpecIntegrityError: RefIdError = _instance_SpecIntegrityError
declare const _instance_SpecVersionError: InstanceType<typeof SpecVersionError>
const _isRefIdError_SpecVersionError: RefIdError = _instance_SpecVersionError

export {}
