// SPDX-License-Identifier: Apache-2.0
//
// GENERATED by scripts/gen-surface-swift.mjs from spec/ref-id.json's `openRPC` document.
// Do not hand-edit — regenerate with `node scripts/gen-surface-swift.mjs`, or check staleness
// with `node scripts/gen-surface-swift.mjs --check`.
//
// One typed reference per declared method (two for a parameter of shape `IdentifierOrParsed`,
// which Swift has no union type for: one reference with every such parameter as String, one with
// every such parameter as ParseResult). A missing symbol, a moved argument label or a changed
// type fails this executable's build — the point of the exercise, since Command Line Tools ship
// neither XCTest nor the Swift Testing macros for a target test to fail instead.
//
// `declaredMethods` plus `checkDeclaredMethodsMatchSpec()` catch the other direction: a spec
// change that adds or removes a method without this file being regenerated, for the (currently
// hypothetical) case where every reference above still happens to type-check.

import Foundation
import RefId

/// Every method name `openRPC.methods` declares (`x-casing.swift` is camelCase — canonical
/// names as-is, so this is the spec's own method names, unchanged).
let declaredMethods: [String] = ["parse", "serialise", "build", "canonicalIdentifier", "sameIdentifier", "samePackage", "covers", "relate", "digest", "validateEnvelope", "canonicalise", "loadSpec", "loadSpecFrom"]

/// Binds every declared method to a typed reference. A line here that fails to compile says its
/// own method is missing, or its label/type has moved, at that line's own comment.
func checkSurfaceReferences() {
    // parse
    let _: (String) throws -> ParseResult = parse(_:)
    // serialise
    let _: (ParseResult) throws -> String = serialise(_:)
    // build
    let _: (BuildParts) throws -> String = build(_:)
    // canonicalIdentifier — IdentifierOrParsed: String variant
    let _: (String) throws -> String = canonicalIdentifier(_:)
    // canonicalIdentifier — IdentifierOrParsed: ParseResult variant
    let _: (ParseResult) throws -> String = canonicalIdentifier(_:)
    // sameIdentifier — IdentifierOrParsed: String variant
    let _: (String, String) -> Bool = sameIdentifier(_:_:)
    // sameIdentifier — IdentifierOrParsed: ParseResult variant
    let _: (ParseResult, ParseResult) -> Bool = sameIdentifier(_:_:)
    // samePackage — IdentifierOrParsed: String variant
    let _: (String, String) -> Bool = samePackage(_:_:)
    // samePackage — IdentifierOrParsed: ParseResult variant
    let _: (ParseResult, ParseResult) -> Bool = samePackage(_:_:)
    // covers — IdentifierOrParsed: String variant
    let _: (String, String) -> Bool = covers(_:_:)
    // covers — IdentifierOrParsed: ParseResult variant
    let _: (ParseResult, ParseResult) -> Bool = covers(_:_:)
    // relate — IdentifierOrParsed: String variant
    let _: (String, String) -> RelateResult? = relate(_:_:)
    // relate — IdentifierOrParsed: ParseResult variant
    let _: (ParseResult, ParseResult) -> RelateResult? = relate(_:_:)
    // digest
    let _: ([String]) throws -> String = digest(_:)
    // validateEnvelope
    let _: (String, Any?) throws -> EnvelopeResult = validateEnvelope(requestedId:envelope:)
    // canonicalise
    let _: (Any?) throws -> String = canonicalise(_:)
    // loadSpec
    let _: () throws -> Spec = loadSpec
    // loadSpecFrom
    let _: (URL) throws -> Spec = loadSpecFrom(_:)
}

/// Compares `declaredMethods` against the embedded specification's own `openRPC.methods`, in
/// both directions, reading the raw JSON directly rather than through `Spec` (an executable
/// target has no `@testable` access to its internal accessors). Returns one problem string per
/// divergence; empty means the two names agree.
func checkDeclaredMethodsMatchSpec() throws -> [String] {
    let urls = try embeddedSpecURLs()
    guard let json = try JSONSerialization.jsonObject(with: try Data(contentsOf: urls.json)) as? [String: Any],
          let openRPC = json["openRPC"] as? [String: Any],
          let methods = openRPC["methods"] as? [[String: Any]] else {
        return ["embedded ref-id.json has no openRPC.methods array to compare against"]
    }
    let specMethods = Set(methods.compactMap { $0["name"] as? String })
    let generated = Set(declaredMethods)
    var problems: [String] = []
    for name in specMethods.subtracting(generated).sorted() {
        problems.append("spec/ref-id.json's openRPC declares method \"\(name)\" that Surface.generated.swift does not — regenerate with scripts/gen-surface-swift.mjs")
    }
    for name in generated.subtracting(specMethods).sorted() {
        problems.append("Surface.generated.swift declares method \"\(name)\" that spec/ref-id.json's openRPC no longer does — regenerate with scripts/gen-surface-swift.mjs")
    }
    return problems
}
