// SPDX-License-Identifier: Apache-2.0
//! GENERATED by `scripts/gen-surface-rust.mjs` from `spec/ref-id.json`'s `openRPC` key. Do not hand-edit.
//!
//! One compile-time binding per declared method: a `const _: fn(...) -> ... = ref_id::<name>;` that
//! fails to build when the function is missing or its signature has moved. Every type is fully
//! qualified (`ref_id::Foo`) on purpose — a name that does not exist in the crate is exactly the kind
//! of failure this file exists to surface, self-contained to the one binding that names it.
//!
//! A parameter typed `IdentifierOrParsed` in the specification gets two bindings for the same method —
//! one with every such parameter as `&str`, one with every such parameter as `&ref_id::ParseResult` —
//! because `IdentifierOrParsed` is not itself a Rust type and today's functions are not generic over
//! the two; one binding of such a pair is expected to fail until the function is made generic.
#![allow(dead_code, non_upper_case_globals)]

// parse -> ref_id::parse
const _: fn(&str) -> Result<ref_id::ParseResult, ref_id::RefIdError> = ref_id::parse;

// serialise -> ref_id::serialise
const _: fn(&ref_id::ParseResult) -> Result<String, ref_id::RefIdError> = ref_id::serialise;

// build -> ref_id::build
const _: fn(&ref_id::BuildParts) -> Result<String, ref_id::RefIdError> = ref_id::build;

// canonicalIdentifier -> ref_id::canonical_identifier
const _: fn(&str) -> Result<String, ref_id::RefIdError> = ref_id::canonical_identifier;
const _: fn(&ref_id::ParseResult) -> Result<String, ref_id::RefIdError> = ref_id::canonical_identifier;

// sameIdentifier -> ref_id::same_identifier
const _: fn(&str, &str) -> bool = ref_id::same_identifier;
const _: fn(&ref_id::ParseResult, &ref_id::ParseResult) -> bool = ref_id::same_identifier;

// samePackage -> ref_id::same_package
const _: fn(&str, &str) -> bool = ref_id::same_package;
const _: fn(&ref_id::ParseResult, &ref_id::ParseResult) -> bool = ref_id::same_package;

// covers -> ref_id::covers
const _: fn(&str, &str) -> bool = ref_id::covers;
const _: fn(&ref_id::ParseResult, &ref_id::ParseResult) -> bool = ref_id::covers;

// relate -> ref_id::relate
const _: fn(&str, &str) -> Option<ref_id::RelateResult> = ref_id::relate;
const _: fn(&ref_id::ParseResult, &ref_id::ParseResult) -> Option<ref_id::RelateResult> = ref_id::relate;

// verdict -> ref_id::verdict
const _: fn(&str, &str) -> Option<ref_id::VerdictResult> = ref_id::verdict;
const _: fn(&ref_id::ParseResult, &ref_id::ParseResult) -> Option<ref_id::VerdictResult> = ref_id::verdict;

// digest -> ref_id::digest
const _: fn(&[String]) -> Result<String, ref_id::RefIdError> = ref_id::digest;

// validateEnvelope -> ref_id::validate_envelope
const _: fn(&str, &serde_json::Value) -> Result<ref_id::EnvelopeResult, ref_id::RefIdError> = ref_id::validate_envelope;

// canonicalise -> ref_id::canonicalise
const _: fn(&serde_json::Value) -> Result<String, ref_id::RefIdError> = ref_id::canonicalise;

// loadSpec -> ref_id::load_spec
const _: fn() -> Result<&'static ref_id::Spec, ref_id::RefIdError> = ref_id::load_spec;

// loadSpecFrom -> ref_id::load_spec_from
const _: fn(&std::path::Path) -> Result<ref_id::Spec, ref_id::RefIdError> = ref_id::load_spec_from;

/// The methods `openRPC` declares, spelled the way this language spells them (`x-casing.rust`).
pub const DECLARED: &[&str] = &["parse", "serialise", "build", "canonical_identifier", "same_identifier", "same_package", "covers", "relate", "verdict", "digest", "validate_envelope", "canonicalise", "load_spec", "load_spec_from"];

/// A spec change without regeneration fails here even where every signature still happens to compile.
#[test]
fn declared_matches_spec() {
    // `Spec::value` is `pub(crate)`, so this reads the embedded JSON text directly rather than
    // through the `Spec` type — `embedded_spec_text` is the one public door to it (`load_spec`
    // returns a `Spec`, not the raw document `openRPC` lives in as arbitrary JSON).
    let (json, _sidecar) = ref_id::embedded_spec_text();
    let root: serde_json::Value = serde_json::from_str(json).unwrap();
    let methods = root["openRPC"]["methods"].as_array().cloned().unwrap_or_default();
    let snake = |name: &str| -> String {
        let mut out = String::new();
        for c in name.chars() {
            if c.is_ascii_uppercase() {
                out.push('_');
                out.push(c.to_ascii_lowercase());
            } else {
                out.push(c);
            }
        }
        out
    };
    let mut from_spec: Vec<String> = methods.iter().filter_map(|m| m.get("name").and_then(serde_json::Value::as_str)).map(snake).collect();
    from_spec.sort();
    let mut declared: Vec<String> = DECLARED.iter().map(|s| s.to_string()).collect();
    declared.sort();
    assert_eq!(declared, from_spec, "surface.rs's DECLARED list has drifted from openRPC.methods — regenerate with `node scripts/gen-surface-rust.mjs`");
}
