# SPDX-License-Identifier: Apache-2.0
"""GENERATED by scripts/gen-surface-python.mjs from spec/ref-id.json's openRPC key. Do not hand-edit.

One annotated binding per declared method: mypy --strict fails when the function is missing or its
signature moved. The runtime test holds DECLARED to the specification and to ref_id.__all__.
"""
from __future__ import annotations

import inspect
import json
import os
import re
from collections.abc import Callable, Sequence
from pathlib import Path

import ref_id

_parse: Callable[[str], ref_id.ParseResult] = ref_id.parse
_serialise: Callable[[ref_id.ParseResult], str] = ref_id.serialise
_build: Callable[[ref_id.BuildParts], str] = ref_id.build
_canonical_identifier: Callable[[str | ref_id.ParseResult], str] = ref_id.canonical_identifier
_same_identifier: Callable[[str | ref_id.ParseResult, str | ref_id.ParseResult], bool] = ref_id.same_identifier
_same_package: Callable[[str | ref_id.ParseResult, str | ref_id.ParseResult], bool] = ref_id.same_package
_covers: Callable[[str | ref_id.ParseResult, str | ref_id.ParseResult], bool] = ref_id.covers
_relate: Callable[[str | ref_id.ParseResult, str | ref_id.ParseResult], ref_id.RelateResult | None] = ref_id.relate
_verdict: Callable[[str | ref_id.ParseResult, str | ref_id.ParseResult], ref_id.VerdictResult | None] = ref_id.verdict
_digest: Callable[[Sequence[str]], str] = ref_id.digest
_validate_envelope: Callable[[str, object], ref_id.EnvelopeResult] = ref_id.validate_envelope
_canonicalise: Callable[[object], str] = ref_id.canonicalise
_load_spec: Callable[[], ref_id.Spec] = ref_id.load_spec
_load_spec_from: Callable[[str | os.PathLike[str]], ref_id.Spec] = ref_id.load_spec_from

# Arity per method, and the parameter names where x-argument-labels makes them part of the contract.
# Every other method takes unlabelled arguments, which Python spells positional-only.
PARAMETERS: dict[str, tuple[int, list[str] | None]] = {
    "parse": (1, None),
    "serialise": (1, None),
    "build": (1, None),
    "canonical_identifier": (1, None),
    "same_identifier": (2, None),
    "same_package": (2, None),
    "covers": (2, None),
    "relate": (2, None),
    "verdict": (2, None),
    "digest": (1, None),
    "validate_envelope": (2, ["requested_id", "envelope"]),
    "canonicalise": (1, None),
    "load_spec": (0, None),
    "load_spec_from": (1, None),
}

DECLARED: list[str] = [
    "BuildError",
    "DigestError",
    "RefIdError",
    "SerialiseError",
    "SpecIntegrityError",
    "SpecVersionError",
    "build",
    "canonical_identifier",
    "canonicalise",
    "covers",
    "digest",
    "embedded_spec_text",
    "load_spec",
    "load_spec_from",
    "parse",
    "relate",
    "same_identifier",
    "same_package",
    "serialise",
    "validate_envelope",
    "verdict",
]


def _declared_from_spec() -> list[str]:
    root = Path(__file__).resolve().parents[2] / "spec" / "ref-id.json"
    doc = json.loads(root.read_text(encoding="utf-8"))["openRPC"]
    assert doc["x-casing"]["python"] == "snake_case"
    live = [m for m in doc["methods"] if "python" not in m.get("x-absent-from", [])]
    names = [re.sub(r"[A-Z]", lambda c: "_" + c.group(0).lower(), m["name"]) for m in live]
    names += [a for m in live for a in m.get("x-deprecated-aliases", {}).get("python", [])]
    names += doc["x-extensions"].get("python", [])
    names += [doc["x-error-type"], *(kind + "Error" for kind in doc["components"]["errors"])]
    return sorted(names)


def test_declared_matches_spec() -> None:
    assert _declared_from_spec() == DECLARED, "regenerate with node scripts/gen-surface-python.mjs"


def test_parameter_kinds() -> None:
    for name, (arity, labels) in PARAMETERS.items():
        params = list(inspect.signature(getattr(ref_id, name)).parameters.values())
        assert len(params) == arity, name
        if labels is None:
            assert all(p.kind is inspect.Parameter.POSITIONAL_ONLY for p in params), name
        else:
            assert [p.name for p in params] == labels, name
            assert all(p.kind is not inspect.Parameter.POSITIONAL_ONLY for p in params), name


def test_declared_are_exported() -> None:
    missing = sorted(set(DECLARED) - set(ref_id.__all__))
    assert not missing, f"ref_id.__all__ lacks {missing}"
